#!/bin/bash

# FlightHub Local Supabase Setup Script
# This script helps you set up a local Supabase instance for development

set -e  # Exit on error

echo "🚀 FlightHub Local Supabase Setup"
echo "=================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if Docker is running
echo "📦 Checking Docker..."
if ! docker info > /dev/null 2>&1; then
    echo -e "${RED}❌ Docker is not running. Please start Docker Desktop first.${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Docker is running${NC}"
echo ""

# Check if Supabase CLI is installed
echo "🔧 Checking Supabase CLI..."
if ! command -v supabase &> /dev/null; then
    echo -e "${RED}❌ Supabase CLI is not installed.${NC}"
    echo "Install it with: brew install supabase/tap/supabase"
    exit 1
fi
echo -e "${GREEN}✓ Supabase CLI is installed ($(supabase --version))${NC}"
echo ""

# No need to link - migrations are already in repo
echo "📦 Using local migrations from supabase/migrations/"
echo "   (No cloud connection needed for local development)"
echo ""

# Start Supabase
echo "🎬 Starting local Supabase..."
echo "This may take a few minutes on first run (downloading Docker images)..."
echo ""

supabase start

if [ $? -ne 0 ]; then
    echo -e "${RED}❌ Failed to start Supabase${NC}"
    exit 1
fi

echo ""
echo -e "${GREEN}✓ Supabase is running!${NC}"
echo ""

# Get credentials
echo "📋 Extracting credentials..."
API_URL=$(supabase status | grep "API URL" | awk '{print $3}')
ANON_KEY=$(supabase status | grep "Publishable key" | awk '{print $3}')
SERVICE_KEY=$(supabase status | grep "Secret key" | awk '{print $3}')
STUDIO_URL=$(supabase status | grep "Studio URL" | awk '{print $3}')

# Create .env.local
echo ""
echo "📝 Creating .env.local..."

cat > .env.local << EOF
# Local Supabase Development Configuration
# Generated by setup-local-supabase.sh

# Local Supabase
NEXT_PUBLIC_SUPABASE_URL=$API_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_KEY

# Local Database
DATABASE_URL=postgresql://postgres:postgres@127.0.0.1:54322/postgres

# Application Settings
NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXT_PUBLIC_APP_NAME=FlightHub
EOF

echo -e "${GREEN}✓ Created .env.local${NC}"
echo ""

# Summary
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}🎉 Local Supabase is ready!${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 Important URLs:"
echo "   • App:     http://localhost:3000"
echo "   • Studio:  $STUDIO_URL"
echo "   • Inbucket (emails): http://127.0.0.1:54324"
echo ""
echo "📝 Next Steps:"
echo "   1. Start dev server:  npm run dev"
echo "   2. Open Studio:       npm run supabase:studio"
echo "   3. Create test user in Studio → Authentication → Users"
echo ""
echo "💡 Helpful Commands:"
echo "   • Stop Supabase:     npm run supabase:stop"
echo "   • Reset database:    npm run supabase:reset"
echo "   • View logs:         npm run supabase:logs"
echo "   • Check status:      npm run supabase:status"
echo ""
echo "📚 Full documentation: LOCAL_DEVELOPMENT.md"
echo ""
echo -e "${YELLOW}Note: Cloud config backed up to .env.cloud${NC}"
echo "      To switch back: cp .env.cloud .env.local"
echo ""
